// <auto-generated />
using System;
using CurrencyCalculatorSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CurrencyCalculatorSystem.Infrastructure.Data.Migrations.Bussiness
{
    [DbContext(typeof(ContextDb))]
    [Migration("20260928152753_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CurrencyCalculatorSystem.Domain.Aggregates.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CurrencyId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyIsoCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("CurrencyIsoCode")
                        .IsFixedLength();

                    b.Property<string>("CurrencyIsoNumber")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("CurrencyIsoNumber")
                        .IsFixedLength();

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CurrencyName");

                    b.Property<DateTime>("CurrencyStartDate")
                        .HasColumnType("date")
                        .HasColumnName("CurrencyStartDate");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CurrencySymbol");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyIsoCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Currencies_IsoCode");

                    b.ToTable("Currencies", (string)null);
                });

            modelBuilder.Entity("CurrencyCalculatorSystem.Domain.Aggregates.FavouriteCurrencies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FavouriteCurrencyId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavouriteCurrency")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("FavouriteCurrency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FavouriteCurrencies", (string)null);
                });

            modelBuilder.Entity("CurrencyCalculatorSystem.Domain.Aggregates.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProviderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProviderCountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("ProviderCountryCode")
                        .IsFixedLength();

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ProviderKey");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ProviderName");

                    b.Property<string>("ProviderPivotCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("ProviderPivotCurrency")
                        .IsFixedLength();

                    b.Property<string>("ProviderRateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ProviderRateType");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Providers_ProviderKey");

                    b.ToTable("Providers", (string)null);
                });

            modelBuilder.Entity("CurrencyCalculatorSystem.Domain.Aggregates.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RateId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrencyBaseId")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyBaseId");

                    b.Property<DateTime>("CurrencyDate")
                        .HasColumnType("date")
                        .HasColumnName("CurrencyDate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<int>("QuoteCurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("QuoteCurrencyId");

                    b.Property<decimal>("RateValue")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("RateValue");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyBaseId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("QuoteCurrencyId");

                    b.HasIndex("CurrencyDate", "CurrencyBaseId", "QuoteCurrencyId", "ProviderId")
                        .IsUnique()
                        .HasDatabaseName("UX_Rates_Date_Base_Quote_Provider");

                    b.ToTable("Rates", (string)null);
                });

            modelBuilder.Entity("CurrencyCalculatorSystem.Domain.Aggregates.Rate", b =>
                {
                    b.HasOne("CurrencyCalculatorSystem.Domain.Aggregates.Currency", "CurrencyBase")
                        .WithMany("BaseRates")
                        .HasForeignKey("CurrencyBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurrencyCalculatorSystem.Domain.Aggregates.Provider", "Provider")
                        .WithMany("Rates")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurrencyCalculatorSystem.Domain.Aggregates.Currency", "QuoteCurrency")
                        .WithMany("QuoteRates")
                        .HasForeignKey("QuoteCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrencyBase");

                    b.Navigation("Provider");

                    b.Navigation("QuoteCurrency");
                });

            modelBuilder.Entity("CurrencyCalculatorSystem.Domain.Aggregates.Currency", b =>
                {
                    b.Navigation("BaseRates");

                    b.Navigation("QuoteRates");
                });

            modelBuilder.Entity("CurrencyCalculatorSystem.Domain.Aggregates.Provider", b =>
                {
                    b.Navigation("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
