<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Configurations\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.31">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CurrencyCalculatorSystem.Application\CurrencyCalculatorSystem.Application.csproj" />
    <ProjectReference Include="..\CurrencyCalculatorSystem.Infrastructure\CurrencyCalculatorSystem.Infrastructure.csproj" />
  </ItemGroup>

</Project>
